# Site settings
title: Philip Shih
description: Philip Shih
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Philip Shih
user_description: Hi! I'm Philip, a 4th year undergraduate student at UC Berkeley. I am particularly interested in radiology, radiation oncology, and deep learning in medical imaging and radiation therapy. I've previously conducted research on TIM-Barrel dynamics through the Klinman Group, and led an independent project on machine learning in fMRI imaging through the Undergraduate Lab at Berkeley.
user_title: 20 | Research Assistant | Developer
email: philipshih@berkeley.edu
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
