# Site settings
title: Philip Shih
description: Philip Shih
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "philipshih.github.io"

# User settings
username: Philip Shih
user_description:
user_title: Student • Developer • Researcher
email: philipshih@berkeley.edu
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
plugins:
  - jekyll-sitemap

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
